# 파이썬 기본문법

# 1. 변수

데이터가 저장된 메모리를 이름으로 정의합니다.

사용법 변수명 = 데이터

In [ ]:
a = 1

In [ ]:
a

1

In [ ]:
b = 22
b

22

In [ ]:
a + b

23

In [ ]:
c = 0.1
a+c

1.1

파이썬은 자동으로 대입연산하는 데이터에따라 자료형이 변경됩니다.

In [ ]:
A = '가'
B = '다'
A+B


'가다'

In [ ]:
A+'나'+B

'가나다'

In [ ]:
A = '가나다라'
A = 1
A

1

## 파이썬의 변수명 작명

다음과 같은 이름은 사용할 수 없습니다.
1. 파이썬의 예약어
2. 숫자로 시작
3. 특수기호 포함
4. 띄어쓰기 포함

In [ ]:
True = '예약어'

SyntaxError: ignored

In [ ]:
1a = 1

SyntaxError: ignored

In [ ]:
A@ = 123

SyntaxError: ignored

In [ ]:
A B = 12

SyntaxError: ignored

## 변수의 주소 확인

In [ ]:
a = '주소'
id(a)

133642470390064

In [ ]:
b = a
id(b)

133642470390064

In [ ]:
a = 1
b

'주소'

In [ ]:
id(a)

133643740102896

In [ ]:
id(b)

133642470390064

### 다양한 변수입력 방법

In [ ]:
a, b, c = ('가', ' 나', '다')
a

'가'

In [ ]:
b

' 나'

In [ ]:
c

'다'

In [ ]:
A=B=C = '가나다'
A

'가나다'

In [ ]:
B

'가나다'

In [ ]:
C

'가나다'

# 2. 자료형

In [ ]:
A = 1 # int
B = 1.1 # float
C = '문자열' # str
D = True # bool

In [ ]:
D

True

### 자료형-리스트

데이터를 연속적을 저장
대괄호를 사용하여 반점(,)으로 각 데이터를 구분

In [ ]:
A = [1,2,3,4,5]
B = ['가', '나', '다', '라', '마']
C = ['가', 1, '나', 2]

In [ ]:
A

[1, 2, 3, 4, 5]

In [ ]:
B

['가', '나', '다', '라', '마']

In [ ]:
C

['가', 1, '나', 2]

리스트의 데이터 찾기
가장 앞 데이터 위치 - 0부터 시작

In [ ]:
A[0]

1

In [ ]:
A[4]

5

In [ ]:
B[2]

'다'

리스트의 뒤부터 찾기

In [ ]:
A[-1]

5

In [ ]:
B[-4]

'나'

리스트 데이터 범위로 찾기
- [찾고자하는 데이터의 위치 시작점:끝점+1]

In [ ]:
A[:]

[1, 2, 3, 4, 5]

In [ ]:
A[2:]

[3, 4, 5]

In [ ]:
A[:4]

[1, 2, 3, 4]

In [ ]:
A[1:3]

[2, 3]

In [ ]:
A[:-1]

[1, 2, 3, 4]

### 다중 리스트

In [ ]:
AA = [[1, 2, [3, 4], 5], [6, 7, 8, 9, 10], 11, 12]
AA

[[1, 2, [3, 4], 5], [6, 7, 8, 9, 10], 11, 12]

다중 리스트에서 데이터 가져오기

In [ ]:
AA[0]

[1, 2, [3, 4], 5]

In [ ]:
AA[0][2]

[3, 4]

In [ ]:
AA[0][2][1]

4

In [ ]:
AA[2]

11

In [ ]:
AA[1][-1]

10

## 리스트 멤버함수

In [ ]:
#리스트에 원소추가
AA.append([13,14])
AA

[[1, 2, [3, 4], 5], [6, 7, 8, 9, 10], 11, 12, [13, 14], [13, 14]]

In [ ]:
# 리스트에 원소 삽입
AA.insert(2, 15)
AA

[[1, 2, [3, 4], 5], [6, 7, 8, 9, 10], 15, 11, 12, [13, 14], [13, 14]]

In [ ]:
# 리스트 정렬
BB = [5,3,0,8,9,7,1]
BB.sort(reverse=True) # 역순정렬
BB

[9, 8, 7, 5, 3, 1, 0]

In [ ]:
# 리스트 반전
BB = [5,3,0,8,9,7,1]
BB.reverse()
BB

[1, 7, 9, 8, 0, 3, 5]

In [ ]:
# 리스트 원소 찾기
AA.index(15)

2

In [ ]:
AA.index([13, 14])

5

In [ ]:
AA[0].index([3,4])

2

In [ ]:
# 특정 원소의 개수
CC = [1,2,2,2,3,3,4,5,6,6,6,6,6,7,8,9,9,9,9]
CC.count(6)

5

리스트 원소 삭제

In [ ]:
del AA[3]
AA # 11삭제됨

[[1, 2, [3, 4], 5], [6, 7, 8, 9, 10], 15, 12, [13, 14], [13, 14]]

In [ ]:
AA.remove([13,14]) #[13, 14]를 삭제
AA

[[1, 2, [3, 4], 5], [6, 7, 8, 9, 10], 15, 12, [13, 14]]

리스트의 연산

In [ ]:
AA + BB # 리스트 합

[[1, 2, [3, 4], 5],
 [6, 7, 8, 9, 10],
 15,
 11,
 12,
 [13, 14],
 [13, 14],
 1,
 7,
 9,
 8,
 0,
 3,
 5]

In [ ]:
BB * 2 # 리스트 곱

[1, 7, 9, 8, 0, 3, 5, 1, 7, 9, 8, 0, 3, 5]

In [ ]:
len(BB) # 리스트 길이

7

In [ ]:
len(AA)

7

## 자료형-튜플

괄호를 사용하여 선언
원소값을 따로 변경 불가능함

In [ ]:
tuple1 = (255, 100 , 0)

In [ ]:
tuple1[0] = 100 # 원소변경시 에러

TypeError: ignored

## 자료형-딕셔너리

key와 value를 한 쌍으로 저장하는 자료형  
dic1 = {key1: value1, key2: value2}

In [ ]:
dic1 = {'name': 'killdong',
        'age': 20,
        'phone': '010-1234-1234',
        'birth': 20031010}
dic1

{'name': 'killdong', 'age': 20, 'phone': '010-1234-1234', 'birth': 20031010}

In [ ]:
# 딕셔너리 키값
dic1.keys()

dict_keys(['name', 'age', 'phone', 'birth'])

In [ ]:
# 딕셔너리 value 값
dic1.values()

dict_values(['killdong', 20, '010-1234-1234', 20031010])

In [ ]:
# 특정 key의 value값
dic1['name']

'killdong'

In [ ]:
# 특정 key값의 value값 변경
dic1['birth'] = 20210505
dic1

{'name': 'killdong', 'age': 20, 'phone': '010-1234-1234', 'birth': 20210505}

In [ ]:
# update 함수를 이용하여 원소 변경 및 추가
dic1.update({'phone': '010-4321-4321'})
dic1

{'name': 'killdong', 'age': 20, 'phone': '010-4321-4321', 'birth': 20210505}

In [ ]:
dic1.update({'height' : 180})
dic1

{'name': 'killdong',
 'age': 20,
 'phone': '010-4321-4321',
 'birth': 20210505,
 'height': 180}

In [ ]:
# key 값으로 value 얻기
dic1.get('age')

20

In [ ]:
# 특정 키값으로 원소 삭제
dic1.pop('age')
dic1

{'name': 'killdong',
 'phone': '010-4321-4321',
 'birth': 20210505,
 'height': 180}

## 다중 딕셔너리

딕셔너리의 key값 내부에 key값과 value값을 넣을 수 있습니다.

In [ ]:
dic2 = {
    '1반' : {
        '1조' : ['김철수', '김영희', '김길동'],
        '2조' : ['이철수', '이발소', '이영희']
    }
}
dic2

{'1반': {'1조': ['김철수', '김영희', '김길동'], '2조': ['이철수', '이발소', '이영희']}}

## 자료형-세트

집합 계산을 위한 자료형.  
{, , , }를 사용하여 자료형 생성.  
데이터의 순서가 없음.  
중복 데이터 없음.  

In [ ]:
AAA = {'가', '나', '다', '라', '가', '나'}
AAA

{'가', '나', '다', '라'}

In [ ]:
# 세트에 원소 추가
AAA.add('마')
AAA

{'가', '나', '다', '라', '마'}

In [ ]:
# 집합을 추가
BBB = {'바', '사', '아'}
AAA.update(BBB)
AAA

{'가', '나', '다', '라', '마', '바', '사', '아'}

In [ ]:
# 특정 원소 제거
AAA.remove('가')
AAA

{'나', '다', '라', '마', '바', '사', '아'}

In [ ]:
# 세트 비우기
AAA.clear()
AAA

set()

# 3. 제어문

## 조건문  
if 조건: -조건이 참이면 :다음에 한 칸 들여쓰여진 코드들을 실행  
elif 조건: - 앞의 if문이 거짓이면 비교를 실행하고 참일 경우 if문과 같이 실행  
else: - 앞의 조건문이 거짓일경우 실행  

a == b : a와 b가 같으면 참  
a != b : a와 b가 다르면 참  
a > b : a가 b 초과이면 참  
a >= b : a가 b 이상이면 참  
a < b : a가 b 미만이면 참  
a <=b : a가 b 이하이면 참  
not a : a가 거짓이면 참  

(A) and (B) : A와 B 두 조건 모두 참이면 참  
(A) or (B) : A와 B 두 조건 중 하나라도 참이면 참  

In [ ]:
list1 = [1,2,3,4,5,6]
list2 = [1,2,3]

if len(list1) > len(list2):
  print('list1에 데이터가 더 많습니다.')
elif len(list1) == len(list2):
  print('list1과 list2가 데이터의 수가 같습니다.')
else:
  print('list2에 데이터가 더 많습니다.')

list1에 데이터가 더 많습니다.


In [ ]:
list3 = list1

if list1 != list2:
  print('list1과 list2는 다릅니다.')
elif list1 == list3:
  print('list1과 list2는 같습니다.')
else:
  print('list1과 list2는 같습니다.')

list1과 list2는 다릅니다.


In [ ]:
a1 = 33
b1 = 0

if a1:
  print('이 조건문은 참입니다.')
else:
  print('이 조건문은 거짓입니다.')

if b1:
  print('이 조건문은 참입니다.')
else:
  print('이 조건문은 거짓입니다.')

if not b1:
  print('이 조건문은 참입니다.')
else:
  print('이 조건문은 거짓입니다.')


이 조건문은 참입니다.
이 조건문은 거짓입니다.
이 조건문은 참입니다.


In [ ]:
if a1 and b1:
  print('둘 다 참입니다.')
else:
  print('둘 중 하나 이상 참이 아닙니다.')

if a1 or b1:
  print('둘 중 하나라도 참입니다.')
else:
  print('둘 다 참이 아닙니다.')

둘 중 하나 이상 참이 아닙니다.
둘 중 하나라도 참입니다.


In [ ]:
c1 = True
d1 = False

if a1 and c1:
  print('둘 다 참입니다.')
else:
  print('둘 중 하나 이상 참이 아닙니다.')

if b1 or d1:
  print('둘 다 참입니다.')
else:
  print('둘 중 하나도 참이 아닙니다.')

둘 다 참입니다.
둘 중 하나도 참이 아닙니다.


In [ ]:
# 리스트 내용 조건문
list1 = [1,2,3,4,5,6]
list2 = [1,2,3]

if 4 in list1:
  print('list1에 4가 있습니다.')
else:
  print('4가 없습니다.')

list1에 4가 있습니다.


In [ ]:
if 4 in list2:
  print('list2에 4가 있습니다.')
else:
  if 4 in list1:
    print('list1에는 4가 있습니다.')
  else:
    print('4가 없습니다.')

list1에는 4가 있습니다.


## 파이썬 산술연산  
a + b  더하기  
a - b  빼기  
a * b  곱하기  
a ** b  제곱  
a / b  나누기  
a // b  몫  
a % b  나머지

## 간단 예제  
돈이 10000원이 있습니다.  
살 수 있는 물건과 단일 품목 구매가능한 최대 수를 출력하세요.


In [ ]:
money = 10000

apple = 2000
banana = 2500
strawberry = 5000
snack = 1500


In [ ]:
if money > apple:
  print(f'사과를 {money//apple}개 구입할 수 있어요.')
if money > banana:
  print(f'바나나를 {money//banana}개 구입할 수 있어요.')
if money > strawberry:
  print(f'딸기를 {money//strawberry}개 구입할 수 있어요.')
if money > snack:
  print(f'과자를 {money//snack}개 구입할 수 있어요.')

사과를 5개 구입할 수 있어요.
바나나를 4개 구입할 수 있어요.
딸기를 2개 구입할 수 있어요.
과자를 6개 구입할 수 있어요.


사과 바나나 딸기 과자 순으로 우선적으로 하나 씩 구매해야합니다.
무엇을 살 수 있을까요?

In [ ]:
money = 10000

if money > apple:
  print(f'사과를 샀어요.')
  money = money - apple
if money > banana:
  print(f'바나나를 샀어요.')
  money -= banana
if money > strawberry:
  print(f'딸기를 샀어요.')
  money -= strawberry
if money > snack:
  print(f'과자를 샀어요.')
  money -= snack
print(f'돈이 {money}원 남았어요.')

사과를 샀어요.
바나나를 샀어요.
딸기를 샀어요.
돈이 500원 남았어요.


# 반복문  
while (조건문): 참이면 계속 반복

In [ ]:
count = 0
while 1:
  count += 1
  print(f'{count}번째 반복입니다.')
  if count > 9:
    break

1번째 반복입니다.
2번째 반복입니다.
3번째 반복입니다.
4번째 반복입니다.
5번째 반복입니다.
6번째 반복입니다.
7번째 반복입니다.
8번째 반복입니다.
9번째 반복입니다.
10번째 반복입니다.


In [ ]:
count = 0
while count < 10:
  count += 1
  print(f'{count}번째 반복입니다.')

1번째 반복입니다.
2번째 반복입니다.
3번째 반복입니다.
4번째 반복입니다.
5번째 반복입니다.
6번째 반복입니다.
7번째 반복입니다.
8번째 반복입니다.
9번째 반복입니다.
10번째 반복입니다.


### for (value) in (iterator)

In [ ]:
for x in range(10): # range(숫자) 범위 지정 0~9
  print(x)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for x in range(5, 15): # range(숫자) 범위 지정 5~14
  print(x)

5
6
7
8
9
10
11
12
13
14


In [ ]:
list1 = [1,2,3,4,5,6,7,8,9]
for x in list1:
  print(x)

1
2
3
4
5
6
7
8
9


In [ ]:
# 딕셔너리 반복문

for key ,value in dic1.items():
  print(key, value)

name killdong
phone 010-4321-4321
birth 20210505
height 180


In [ ]:
for x ,y in dic1.items():
  print(x, y)

name killdong
phone 010-4321-4321
birth 20210505
height 180


In [ ]:
dic2['1반']['2조'][0]

'이철수'

In [ ]:
for d in dic2['1반']:
  print(d)

1조
2조


In [ ]:
for d in dic2['1반']['1조']:
  print(d)

김철수
김영희
김길동


In [ ]:
list1 = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
for x in list1:
  if x%2 ==0:
    continue # 짝수일경우 넘기고 다음 x로 실행
  print(x)

1
3
5
7
9
11
13
15
17
19


In [ ]:
list1 = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
for x in list1:
  if x%2 ==0:
    break # 짝수일경우 반복문 종료
  print(x)

1


노래가사에 특정 단어가 몇 개 들어있는지 확인해봅니다.

In [ ]:
ttls = '''
Twinkle, twinkle, little star,
How I wonder what you are!
Up above the world so high,
Like a diamond in the sky!

When the blazing sun is gone,
When the nothing shines upon,
Then you show your little light,
Twinkle, twinkle, all the night.

Then the traveller in the dark,
Thanks you for your little spark,
He could not see which way to go,
If you did not twinkle so.

In the dark blue sky you keep,
And often through my curtains peep,
For you never shut your eye,
Till the sun is in the sky.

As your bright and tiny spark,
Lights the traveller in the dark,
Though I know not what you are,
Twinkle, twinkle, little star
'''

In [ ]:
ttls = ttls.replace(',', '')

In [ ]:
ttls = ttls.replace('?', '')

In [ ]:
ttls = ttls.replace('\n', '')

In [ ]:
ttls = ttls.replace('(', '')

In [ ]:
ttls = ttls.replace(')', '')

In [ ]:
lyrics = ttls.split(' ')

In [ ]:
lyrics

['Twinkle',
 'twinkle',
 'little',
 'starHow',
 'I',
 'wonder',
 'what',
 'you',
 'are!Up',
 'above',
 'the',
 'world',
 'so',
 'highLike',
 'a',
 'diamond',
 'in',
 'the',
 'sky!When',
 'the',
 'blazing',
 'sun',
 'is',
 'goneWhen',
 'the',
 'nothing',
 'shines',
 'uponThen',
 'you',
 'show',
 'your',
 'little',
 'lightTwinkle',
 'twinkle',
 'all',
 'the',
 'night.Then',
 'the',
 'traveller',
 'in',
 'the',
 'darkThanks',
 'you',
 'for',
 'your',
 'little',
 'sparkHe',
 'could',
 'not',
 'see',
 'which',
 'way',
 'to',
 'goIf',
 'you',
 'did',
 'not',
 'twinkle',
 'so.In',
 'the',
 'dark',
 'blue',
 'sky',
 'you',
 'keepAnd',
 'often',
 'through',
 'my',
 'curtains',
 'peepFor',
 'you',
 'never',
 'shut',
 'your',
 'eyeTill',
 'the',
 'sun',
 'is',
 'in',
 'the',
 'sky.As',
 'your',
 'bright',
 'and',
 'tiny',
 'sparkLights',
 'the',
 'traveller',
 'in',
 'the',
 'darkThough',
 'I',
 'know',
 'not',
 'what',
 'you',
 'areTwinkle',
 'twinkle',
 'little',
 'star']

In [ ]:
count = 0
for x in lyrics:
  if x.lower() == 'little':
    count += 1
print(f'little이 {count}개 있어요.')

little이 4개 있어요.


In [ ]:
count = 0
for x in lyrics:
  if 'little' in x.lower():
    count += 1
print(f'little이 {count}개 있어요.')

little이 4개 있어요.


In [ ]:
for num, text in enumerate(lyrics): # 인덱스번호와 출력
  print(num, text)

0 Twinkle
1 twinkle
2 little
3 starHow
4 I
5 wonder
6 what
7 you
8 are!Up
9 above
10 the
11 world
12 so
13 highLike
14 a
15 diamond
16 in
17 the
18 sky!When
19 the
20 blazing
21 sun
22 is
23 goneWhen
24 the
25 nothing
26 shines
27 uponThen
28 you
29 show
30 your
31 little
32 lightTwinkle
33 twinkle
34 all
35 the
36 night.Then
37 the
38 traveller
39 in
40 the
41 darkThanks
42 you
43 for
44 your
45 little
46 sparkHe
47 could
48 not
49 see
50 which
51 way
52 to
53 goIf
54 you
55 did
56 not
57 twinkle
58 so.In
59 the
60 dark
61 blue
62 sky
63 you
64 keepAnd
65 often
66 through
67 my
68 curtains
69 peepFor
70 you
71 never
72 shut
73 your
74 eyeTill
75 the
76 sun
77 is
78 in
79 the
80 sky.As
81 your
82 bright
83 and
84 tiny
85 sparkLights
86 the
87 traveller
88 in
89 the
90 darkThough
91 I
92 know
93 not
94 what
95 you
96 areTwinkle
97 twinkle
98 little
99 star


# 4. 함수

def 함수명(매개변수1, 매개변수2 ....):  
&nbsp;&nbsp;내용

In [ ]:
def add(x, y):
  return x + y

In [ ]:
add(1, 2)

3

In [ ]:
def print_fuc():
  print('함수입니다.')

In [ ]:
print_fuc()

함수입니다.


In [ ]:
def func1(a: int=1, b: int=2, c: float=3.5):
  return a+b+c, a*b*c, c-b-a

In [ ]:
a, b, c = func1()
print(a, b, c)

6.5 7.0 0.5


In [ ]:
a, b, c = func1(10, 20, 100.7)
print(str(a)+'|'+str(b)+'|'+str(c))

130.7|20140.0|70.7


In [ ]:
# 숫자를 입력받아 해당 숫자의 배수를 뺀 20이하의 수 리스트
def func2(n):
  list1 = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
  output_list = []
  for x in list1:
    if x%n ==0:
      continue
    print(x)
    output_list.append(x)
  return output_list

In [ ]:
func2(3)

1
2
4
5
7
8
10
11
13
14
16
17
19
20


In [ ]:
output = func2(3)

1
2
4
5
7
8
10
11
13
14
16
17
19
20


In [ ]:
output

[1, 2, 4, 5, 7, 8, 10, 11, 13, 14, 16, 17, 19, 20]

## 5. 입출력

In [ ]:
input()

test


'test'

In [ ]:
num = input("원하는 수 입력: ")

원하는 수 입력: 10


In [ ]:
num

'10'

In [ ]:
num = input("원하는 수 입력: ")
print('입력한 숫자는 '+num+' 입니다.')

원하는 수 입력: 15
입력한 숫자는 15 입니다.


In [ ]:
output_text = '출력문입니다.'
number = 1234
print('출력문입니다.')
print(output_text)
print('%s' %output_text)
print('숫자를 출력합니다.', number, ' 를 출력했습니다.')
print('숫자를 string으로 바꾼 후 출력합니다.' + str(number) + ' 를 문자열로 변경 후 출력했습니다.')
print(f'숫자를 출력합니다. {number} 를 출력했습니다.')
print('숫자를 출력합니다. {} 를 출력했습니다.'.format(number))
print('실수를 출력합니다. {:.5f}'.format(1.0123456789))
print('돈을 출력하는데 좋습니다. {:,}원'.format(100000000000))

출력문입니다.
출력문입니다.
출력문입니다.
숫자를 출력합니다. 1234  를 출력했습니다.
숫자를 string으로 바꾼 후 출력합니다.1234 를 문자열로 변경 후 출력했습니다.
숫자를 출력합니다. 1234 를 출력했습니다.
숫자를 출력합니다. 1234 를 출력했습니다.
실수를 출력합니다. 1.01235
돈을 출력하는데 좋습니다. 100,000,000,000원


### 체질량지수 BMI계산하기

In [ ]:
height = float(input('키를 입력하세요.(cm) : '))
gender = input('성별을 입력하세요.(m or f) : ')
weight = float(input('체중을 입력하세요(kg) : '))

if gender.lower() == 'm':
  mul=22
else:
  mul=21
bmi = (weight/(((height/100)**2)*mul)) * 100
print('BMI는 {}% 입니다.'.format(round(bmi,3)))

status = ['저체중', '정상체중', '과체중', '경도비만', '중정도비만', '고도비만']
bmi_list = [90, 110, 120, 130, 160]
result = 0
for i in bmi_list:
  if bmi < i:
    break;
  else:
    result += 1
print(f'{status[result]} 입니다.')

키를 입력하세요.(cm) : 184
성별을 입력하세요.(m or f) : m
체중을 입력하세요(kg) : 80
BMI는 107.407% 입니다.
정상체중 입니다.


In [ ]:
f = open("test.txt", 'w')
text = '텍스트입니다.'
f.write(text)
f.close()

In [ ]:
f = open("test.txt", 'r')
print(f.read())
f.close()

텍스트입니다.


In [ ]:
height = float(input('키를 입력하세요.(cm) : '))
gender = input('성별을 입력하세요.(m or f) : ')
weight = float(input('체중을 입력하세요(kg) : '))

if gender.lower() == 'm':
  mul=22
else:
  mul=21
bmi = (weight/(((height/100)**2)*mul)) * 100
print('BMI는 {}% 입니다.'.format(round(bmi,3)))

status = ['저체중', '정상체중', '과체중', '경도비만', '중정도비만', '고도비만']
bmi_list = [90, 110, 120, 130, 160]
result = 0
for i in bmi_list:
  if bmi < i:
    break;
  else:
    result += 1
print(f'{status[result]} 입니다.')

f = open("log.txt", 'a')

f.write(str(bmi)+'\n')

f.close()

키를 입력하세요.(cm) : 168
성별을 입력하세요.(m or f) : f
체중을 입력하세요(kg) : 55
BMI는 92.795% 입니다.
정상체중 입니다.


In [ ]:
with open("log.txt", 'r') as f:
  print(f.read())
  f.close()

104.72160164976798
92.79505452974843



# 6. 라이브러리

외부 라이브러리 설치 pip  
pip install '패키지 이름'

In [1]:
pip install numpy

In [2]:
pip install pandas


## numpy

In [4]:
import numpy as np

In [5]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr2 = np.array([11,12,13,14,15,16,17,18,19])

arr1 + arr2

array([12, 14, 16, 18, 20, 22, 24, 26, 28])

In [9]:
arr1 * arr2

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171])

In [10]:
np.dot(arr1, arr2)

735

In [11]:
# 슬라이싱
arr1[3:7]

array([4, 5, 6, 7])

In [12]:
arr1[:-3]

array([1, 2, 3, 4, 5, 6])

In [14]:
# numpy.array의 맴버함수들

np.sum(arr1)

45

In [15]:
np.max(arr1)

9

In [17]:
np.min(arr1)

1

In [18]:
np.mean(arr1)

5.0

In [23]:
np.argmax(arr1) # 최대값의 인덱스

8

In [19]:
arr1.reshape(3,3) # 2차원으로

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr_2d.reshape(-1) # 1차원으로

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# 역행렬
arr3 = np.array([[4,3,2],[7,6,5],[14,21,13]])
np.linalg.inv(arr3)

array([[ 0.6       , -0.06666667, -0.06666667],
       [ 0.46666667, -0.53333333,  0.13333333],
       [-1.4       ,  0.93333333, -0.06666667]])

In [29]:
# 전치행렬
arr3.T

array([[ 4,  7, 14],
       [ 3,  6, 21],
       [ 2,  5, 13]])

In [32]:
# 고유값, 고유벡터

eigen_value, eigen_vector = np.linalg.eig(arr3)
print(eigen_value)
print(eigen_vector)

[22.91429632  1.44487743 -1.35917376]
[[ 0.151757    0.52930291  0.01254812]
 [ 0.33743512  0.11003373 -0.57007869]
 [ 0.92903571 -0.8412675   0.82149427]]


In [33]:
# SVD (특이값분해)
u, s, v_t = np.linalg.svd(arr3)
print(u)
print(s)
print(v_t.T)

[[-0.16870376 -0.52480895 -0.83433483]
 [-0.33534236 -0.76541246  0.54926248]
 [-0.92686814  0.37245045 -0.04686271]]
[30.60968488  2.7872928   0.52743757]
[[-0.52265698 -0.80465771 -0.28170136]
 [-0.71815167  0.59360751 -0.36316429]
 [-0.45944299 -0.01249395  0.88811938]]


## pandas

In [34]:
import pandas as pd

In [35]:
data = {'이름': ['홍길동', '김철수', '김영희', '흰둥이'],
        '나이': [20, 30, 31, 15],
        '도시': ['한양', '서울', '인천', '광주']}

df = pd.DataFrame(data)
df

이름  나이  도시
0  홍길동  20  한양
1  김철수  30  서울
2  김영희  31  인천
3  흰둥이  15  광주

In [44]:
# 기본정보
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   이름      4 non-null      object
 1   나이      4 non-null      int64 
 2   도시      4 non-null      object
 3   성별      4 non-null      object
dtypes: int64(1), object(3)
memory usage: 256.0+ bytes


In [45]:
# 통계
df.describe()

나이
count   4.000000
mean   24.000000
std     7.788881
min    15.000000
25%    18.750000
50%    25.000000
75%    30.250000
max    31.000000

In [36]:
df['이름']

0    홍길동
1    김철수
2    김영희
3    흰둥이
Name: 이름, dtype: object

In [37]:
df['나이']

0    20
1    30
2    31
3    15
Name: 나이, dtype: int64

In [38]:
df.loc[2] # 행 가져오기

이름    김영희
나이     31
도시     인천
Name: 2, dtype: object

In [42]:
# 조건 검색
df[df['나이'] > 25]

이름  나이  도시  성별
1  김철수  30  서울  남자
2  김영희  31  인천  여자

In [43]:
df.loc[df['나이'] > 25, ['이름', '도시']]

이름  도시
1  김철수  서울
2  김영희  인천

In [39]:
# 데이터 추가
df['성별'] = ['남자', '남자', '여자', '남자']

In [40]:
df

이름  나이  도시  성별
0  홍길동  20  한양  남자
1  김철수  30  서울  남자
2  김영희  31  인천  여자
3  흰둥이  15  광주  남자

In [46]:
# null값 찾기
df.isnull()

이름     나이     도시     성별
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False

In [47]:
# null값 채우기
df.fillna(0, inplace=True)

In [48]:
# 정렬
df.sort_values(by='나이')

이름  나이  도시  성별
3  흰둥이  15  광주  남자
0  홍길동  20  한양  남자
1  김철수  30  서울  남자
2  김영희  31  인천  여자

In [51]:
# 열 삭제
df.drop('도시', axis=1)

이름  나이  성별
0  홍길동  20  남자
1  김철수  30  남자
2  김영희  31  여자
3  흰둥이  15  남자

In [52]:
# 행 삭제
df.drop(1)

이름  나이  도시  성별
0  홍길동  20  한양  남자
2  김영희  31  인천  여자
3  흰둥이  15  광주  남자

In [54]:
# 조건으로 새로운 데이터 생성
df['상태'] = df['나이'].apply(lambda x: '젊음' if x < 30 else '늙음')
df

이름  나이  도시  성별  상태
0  홍길동  20  한양  남자  젊음
1  김철수  30  서울  남자  늙음
2  김영희  31  인천  여자  늙음
3  흰둥이  15  광주  남자  젊음

In [55]:
# 데이터프레임 합치
df2 = pd.DataFrame({
    '이름': ['이철수'],
    '나이': ['26'],
    '도시': ['강릉'],
    '성별': ['남자'],
    '상태': ['젊음']
})

df = pd.concat([df, df2], ignore_index=True)
df

이름  나이  도시  성별  상태
0  홍길동  20  한양  남자  젊음
1  김철수  30  서울  남자  늙음
2  김영희  31  인천  여자  늙음
3  흰둥이  15  광주  남자  젊음
4  이철수  26  강릉  남자  젊음

In [57]:
# 피봇 테이블
df.pivot_table(index='이름', values='나이')

나이
이름       
김영희  31.0
김철수  30.0
이철수  26.0
홍길동  20.0
흰둥이  15.0

In [58]:
# 입출력
df.to_csv('output.csv', index=False)

In [59]:
opened_df = pd.read_csv('output.csv')
opened_df

이름  나이  도시  성별  상태
0  홍길동  20  한양  남자  젊음
1  김철수  30  서울  남자  늙음
2  김영희  31  인천  여자  늙음
3  흰둥이  15  광주  남자  젊음
4  이철수  26  강릉  남자  젊음